# Generated by Django 4.2.5 on 2023-09-14 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Education", "Education"),
                            ("Health", "Health"),
                            ("Travel", "Travel"),
                            ("Electronics", "Electronics"),
                            ("Investment", "Investment"),
                            ("Clothing", "Clothing"),
                            ("Food", "Food"),
                            ("Entertainment", "Entertainment"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("credit_card", models.BooleanField(default=None)),
                (
                    "day_to_receive_the_analysis",
                    models.DateField(default=datetime.date(2023, 9, 14)),
                ),
                ("description", models.CharField(default=None, max_length=250)),
                (
                    "data_of_purchase",
                    models.DateField(default=datetime.date(2023, 9, 14)),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 9, 14, 1, 54, 32, 931025)
                    ),
                ),
                ("updated_at", models.DateTimeField(default=None)),
            ],
        ),
    ]
