# Generated by Django 4.2.5 on 2023-09-18 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[users.models.validate_min_value_of_decimal_field],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Education", "Education"),
                            ("Health", "Health"),
                            ("Travel", "Travel"),
                            ("Electronics", "Electronics"),
                            ("Investment", "Investment"),
                            ("Clothing", "Clothing"),
                            ("Food", "Food"),
                            ("Entertainment", "Entertainment"),
                            ("Home", "Home"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "credit_card",
                    models.CharField(
                        choices=[("Yes", "sim"), ("No", "Não")], max_length=12
                    ),
                ),
                (
                    "day_to_receive_the_analysis",
                    models.DateField(blank=True, null=True),
                ),
                ("description", models.CharField(max_length=250)),
                (
                    "data_of_purchase",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
