# Generated by Django 4.2.5 on 2023-09-14 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 14, 1, 55, 58, 62943)
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="credit_card",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="description",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
