# Generated by Django 4.2.5 on 2023-09-14 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_purchase_created_at_alter_purchase_credit_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 14, 1, 57, 31, 990360, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="data_of_purchase",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 14, 1, 57, 31, 990343, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
