# Generated by Django 4.2.5 on 2023-09-14 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_purchase_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 14, 1, 58, 24, 1603, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="data_of_purchase",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 14, 1, 58, 24, 1583, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="day_to_receive_the_analysis",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 14, 1, 58, 24, 1535, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
