# Generated by Django 4.2.5 on 2023-09-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_purchase_day_to_receive_the_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='day_to_receive_the_analysis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
