# Generated by Django 4.2.5 on 2023-09-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_purchase_day_to_receive_the_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='credit_card',
            field=models.CharField(choices=[('Yes', 'sim'), ('No', 'Não')], max_length=12),
        ),
    ]
