# Generated by Django 4.2.5 on 2023-09-15 13:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_purchase_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[users.models.validate_min_value_of_decimal_field],
            ),
        ),
    ]
